### DISCUSSION TITLE
New User Guide

### DISCUSSION THREAD

**Discussion by maotian06** [uclahs-cds/tool-NFTest#14] [General]
## 1. Installation

First install the `nftest` in the cluster:

```
pip install git+ssh://git@github.com/uclahs-cds/tool-NF-test.git
```

If any branch is needed, using:

```
pip install git+ssh://git@github.com/uclahs-cds/tool-NF-test.git@branch-name
```

To check if the nftest is installed, run

```
nftest -h
```

The output should be:

```
usage: nf-test [-h] [-V] [CONFIG] {init} ...

positional arguments:
  CONFIG         Path the the nextflow test config YAML file. If not given, it looks for nf-test.yaml or nf-test.yml
  {init}
    init         Initialize nftest.

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  Version
```

## 2. Set up the initial test case

To set up a simple test case, first, spin a F32 or a F72 node, and change the directory to a pipeline directory. 

Then run the following command to initiate the test folder.

```
nftest init
```

It will create one `nftest.yml` file under the current directory and a `test` folder with a `global.config` inside.

Open the `nftest.yml` , there will be two sections, `global` and `cases`. No change is needed for the `global` section. For the `case` section, write the specific pipeline input, here is an example:

```
cases:
  - name: test-multi-sample
    message: running nftest on development branch of call-sSNV
    skip: false
    nf_script: pipeline/call-sSNV.nf
    nf_config: test/test_mutect2/test_multi_tumor/test-tumor.config
    params_file: test/test_mutect2/test_multi_tumor/test-multi-tumor.yaml
    verbose: true
```

Then run the following command `nftest`. The test should start in the terminal.
